#!/usr/bin/node

// This must be set BEFORE out.js is required for the debug info to show up
process.env.DEBUG='*';

const out = require('./src/out.js');

process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin.on('data', function(data) {
    out(JSON.parse(data), (result) => {
        process.oob1 = fs.createWriteStream(null, { fd: 3 });
        process.oob1.write(result);
    });
});